### ISSUE TITLE
[Feature Request] Inverter Soft Limit Control

### ISSUE THREAD

**Issue by callifo** [redpomodoro/fronius_modbus#43]
Thanks for all the great effort, this integration is awesome. We have live pricing based on the wholesale price of electricity so prices can go negative and require you pay money if you export during this time. The Fronius Gen24 seems to have a soft export control limit that can stop the inverter sending any power to the grid, but allow for self-consumption.

Any chance this integration could incorporate Export limitation using this
https://community.home-assistant.io/t/automate-fronius-soft-limit/465124/154

```
  - service: modbus.write_register
    data:
      unit: 1
      hub: mb_fronius
      address: 40236
      value: "0"
  - service: modbus.write_register
    data:
      unit: 1
      hub: mb_fronius
      address: 40232
      value: "{{ states.sensor.solar_trim_percent_when_greater_load.state }}"
  - service: modbus.write_register
    data:
      unit: 1
      hub: mb_fronius
      address: 40236
      value: "1
```

Thanks
